[build]
  publish = "."

# Send a notification email on form submissions
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Configure form notification to your inbox
[notifications]
  [[notifications.forms]]
    # This uses Netlify Notifications. In your Netlify Site settings > Notifications,
    # add an email notification for "Form submissions" to lzy7th@gmail.com
    # (Netlify does not read an address from netlify.toml directly for privacy).
    form = "contact"
    to = "email"

# netlify.toml

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache"
    X-Content-Type-Options = "nosniff"

# 🔒 Optional Security Boost (Best Practices / Lighthouse Security)
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
